
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';

export const SET_RESULT_DATA = 'SET_RESULT_DATA';
export const SET_SEARCH_RESULT_DATA = 'SET_SEARCH_RESULT_DATA';

export const FETCH_SEARCH_MOVIE = 'FETCH_SEARCH_MOVIE'
