
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_SEARCH_MOVIE = 'FETCH_SEARCH_MOVIE';
export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';

export const SET_RESULT_DATA = 'SET_RESULT_DATA';
export const SET_SEARCH_RESULT_DATA = 'SET_SEARCH_RESULT_DATA';
export const SET_MOVIE_DETAILS = 'SET_MOVIE_DETAILS';

export const SET_FETCH_ERROR = 'SET_FETCH_ERROR';

