
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';

export const SET_RESULT_DATA = 'SET_RESULT_DATA';
export const SET_RESULT_ERROR = 'SET_RESULT_ERROR';
